### ISSUE TITLE
Rename RL-Dummy-Classes-v3

### ISSUE THREAD

**Issue by Fiv3286** [RocketLeagueMapmaking/UDK_RL_Setup#2]
just a quick heads-up, the script expects the folder to be called RL-Dummy-Classes. Really easy to fix, but still an additional step :)

**Comment by spencerarrasmith** [comment]
About a month ago I forked the RL-Dummy-Classes-v3 repo to here: https://github.com/RocketLeagueMapmaking/RL-Dummy-Classes

The newest version of the install script should point to that repo instead, since it is the one that's going to get updates going forward.

Are you running the most recent version of this script?

**Comment by Fiv3286** [comment]
I think the script was alright. I see you've removed the directories, which solves the problem entirely :). sorry for the late reply
